extends:
- eslint:recommended
- plugin:@typescript-eslint/eslint-recommended
- plugin:@typescript-eslint/recommended
- prettier
plugins:
- import
- '@typescript-eslint'
- prettier
parserOptions:
  ecmaVersion: 2018
  sourceType: module
env:
  commonjs: true
  browser: true
  node: true
  webextensions: true
  es6: true
globals:
  PRODUCTION: false
rules:
  eol-last:
  - error
  - always
  complexity:
  - error
  - max: 10
  indent:
  - error
  - 2
  - SwitchCase: 1
  max-depth:
  - error
  - max: 3
  max-nested-callbacks:
  - error
  - max: 2
  max-params:
  - error
  - max: 4
  max-statements:
  - error
  - max: 15
  - ignoreTopLevelFunctions: false
  max-len:
  - error
  - code: 120
    ignoreUrls: true
  max-lines:
  - error
  - max: 250
    skipComments: true
    skipBlankLines: true
  semi:
  - error
  - always
  space-before-blocks:
  - error
  - always
  space-before-function-paren:
  - error
  - anonymous: always
    named: never
    asyncArrow: always
  space-in-parens:
  - error
  - never
  import/order:
  - warn
  space-infix-ops:
  - error
  - int32Hint: false
  object-curly-spacing:
  - error
  - always
  no-multi-spaces:
  - error
  prettier/prettier:
  - warn
